name: Android PR Checks

on:
  pull_request:
    branches:
      - main
      - develop
      - release/**

jobs:
  # Step 1: Checkout the Code
  checkout_code:
    name: Checkout Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

  # Step 2: Set Up JDK and Cache Gradle Dependencies
  setup_environment:
    name: Set Up JDK and Gradle Cache
    runs-on: ubuntu-latest
    needs: checkout_code
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

  # Step 3: Run Ktlint Check
  run_ktlint:
    name: Run Ktlint
    runs-on: ubuntu-latest
    needs: setup_environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Ktlint
        run: ./gradlew ktlintCheck --stacktrace

  # Step 4: Run Unit Tests
  run_unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: setup_environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Upload Unit Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: '**/build/test-results/testDebugUnitTest/'

  # Step 5: Run Lint Check
  run_lint:
    name: Run Lint Check
    runs-on: ubuntu-latest
    needs: setup_environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Android Lint
        run: ./gradlew lint --stacktrace

      - name: Upload Lint Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: lint-results
          path: '**/build/reports/lint-results.xml'
