name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Access ACCESS_KEY
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        run: echo $ACCESS_KEY=\"$ACCESS_KEY\" > ./local.properties
      - name: Build the app
        run: ./gradlew assembleDebug
